name: Download and Split File

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download_and_split:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download and Split File
      run: |
        pip install -r requirements.txt
        python download_dns.py

    - name: Upload Artifacts
<<<<<<< HEAD
      uses: actions/upload-artifact@v4  
=======
      uses: actions/upload-artifact@v4
>>>>>>> eb8abb90faf8ea2d7c202305d6840780f0e570de
      with:
        name: DNS-Wild-Files
        path: |
          dns_wild_1.dns
          dns_wild_2.dns
